### PR TITLE
Fix `locals` config option

### PR DESCRIPTION
**Pull request by pschilly**
In the current build the "locals" config item does nothing.

This PR fixes that functionality so that one can dynamically assign the preferred locales.

Changes the default config item to: `NULL` so as to maintain the existing options of "Arabic, English" but one can change it simply to an array of `['en']` or others to change those options out.

## Summary by CodeRabbit

- **Documentation**
	- Added a new section "Config Locales" in the README for localization instructions.
	- Updated the "Auto Caching" section for clarity and added supported cache stores.
	- Revised the "Use Type Component" section for improved formatting.

- **Configuration Changes**
	- Updated the 'locals' setting in the configuration to be `NULL`, clarifying language options.

- **Functionality Updates**
	- Modified the `locals` method to retrieve localization settings dynamically rather than through a parameter.

### CODE REVIEW

**Comment by 3x1io** [comment]
hi @pschilly can you check the comments of Code Rabbit? and run tests locally because you have a problem with testing 

```
────────────────────────────────────────────────────────────────────────────  
   FAILED  Tests\src\TypeColumnTest > it can render type colu…  ViewException   
  Accessing static property TomatoPHP\FilamentTypes\FilamentTypesPlugin::$locals as non static (View: /home/runner/work/filament-types/filament-types/vendor/orchestra/testbench-core/laravel/storage/framework/views/a168b0ebcff266df6b662fc4b6d06e88.blade.php)

  at src/FilamentTypesPlugin.php:21
     17▕      * @return $this
     18▕      */
     19▕     public function locals()
     20▕     {
  ➜  21▕         return (!is_null(config('filament-types.locals'))) ? config('filament-types.locals') : $this->locals;
     22▕     }
     23▕ 
     24▕     public function getLocals(): array
     25▕     {

  1   src/FilamentTypesPlugin.php:26
  2   src/Filament/Resources/TypeResource.php:24

```

**Comment by pschilly** [comment]
@3x1io seen - pushed fix.

**Comment by pschilly** [comment]
Not sure how to have the bot redo the tests - but I did push a fix for the bug that you mentioned @3x1io

**Comment by 3x1io** [comment]
@coderabbitai

**Pull request merged**
